package com.example.ProductList.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.ArrayList;
import java.util.List;

@Getter
@Setter
@Document(collection = "products")
@ApiModel(description = "data model of product entity")
public class Product {
    @Id
    @ApiModelProperty("id generated by db automatically")
    private String id;

    @ApiModelProperty("product name from 5 to 50 chars")
    private String name;

    @ApiModelProperty("product descriptions")
    private String descriptions;

    private Integer kcal;

    @JsonIgnore
    private List<ProductList> productList = new ArrayList<>();
}
