package com.example.ProductList.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.ArrayList;
import java.util.List;

@Getter
@Setter
@Document(collection = "product_list")
@ApiModel(description = "data model of product list entity")
public class ProductList {
    @Id
    @ApiModelProperty("id generated by db automatically")
    private String id;

    @ApiModelProperty("product name from 5 to 30 chars")
    private String name;

    @JsonIgnore
    private List<Product> products = new ArrayList<>();

    public void addProduct(Product product) {
        products.add(product);
    }
}
